- src/utils/data.js
- src/utils/index.js
Freeze emoji data, so vue doesn't have to watch for the changes (which don't happen since we just render a static list of emoji).
> Freeze emoji data

- src/utils/data.js
Fix for the https://github.com/serebrov/emoji-mart-vue/pull/3, make uncompress return the data, it feels more natural, so we can avoid data = uncompress(data) or functoin(uncompress(data)) issues.
Also we are free to change `uncompress` to avoid mutating original data if we'll need it.
> Make uncompress return the resulting data

- README.md
- src/components/category.vue
- src/components/emoji/nimbleEmoji.vue
- src/components/picker/nimblePicker.vue
- src/components/preview.vue
- src/utils/emoji-data.js
- src/utils/shared-props.js
Making it in javascript adds a slowdown (we have a lot of emojis and inline styles increase amount of HTML noticeably).
The default properties can be overwritten via css.
> Use css to set emoji size and background.

- src/utils/emoji-data.js
- src/utils/index.js
- src/utils/nimble-emoji-index.js
It hides the fact that there is a (quite complex) getData call behind it, so we have code like this:
pool[emojiId] = getData(emoji, null, null, this.data)
this.emojis[emojiId] = getSanitizedData(emoji, null, null, this.data)
It is not obvious, but we actually call getData twice here. Now this is changed to
pool[emojiId] = getData(emoji, null, null, this.data)
this.emojis[emojiId] = getSanitizedData(pool[emojiId])
And, since, there is no getSanitizedData anymore, we guarantee that no such error will be made in the future.
> Remove getSanitizedData function.

- src/components/category.vue
- src/utils/emoji-data.js
The enter, leave and click handlers now will receive the emoji with selected skin tone (if available).
> Send skin-color version of the emoji to handlers

- README.md
- css/emoji-mart.css
- docs/app.vue
- package.json
- spec/__snapshots__/picker-spec.js.snap
- spec/picker-spec.js
- src/components/category.vue
- src/components/picker/nimblePicker.vue
- src/utils/emoji-data.js
The `emojiSize` property controls two things: 
1) the width of the picker 
2) the size of the `span` with emoji (and font-size for native emoji)
The "2" was disabled in [this PR](https://github.com/serebrov/emoji-mart-vue/pull/8) as more HTML to render was one of the reasons that slowed down the picker.
But it is not very convenient: now, to change the emoji size we need to both set the `emojiSize` property and override the CSS.
Now, after some more performance testing, it has shown that adding width/height and font size to the HTML doesn't have a big effect on the performance, so the "2" can be re-enabled.
> Re-enable emojiSize property

- spec/emoji-index-spec.js
- src/index.js
- src/utils/emoji-data.js
There is `Emoji` class that represents emoji data, but there is also `Emoji` component.
This PR renames `Emoji` to `EmojiData` (the class with logic), the component name remains `Emoji`.
> Rename emoji class

- docs/webpack.config.js
- package.json
- src/components/emoji/emoji.vue
- src/components/picker/picker.vue
- src/utils/emoji-data.js
- src/webpack.config.js
The json data was removed from the bundle (marked as "external" for webpack), but this bundle was broken due to that: it tried to include json as "../../../data/all.json" while the bundle is under "dist/emoji-mart.js" and the path to the data from it is "../data/all.json".
This PR adds a path alias, so we can always refer the data as "../data/all.json" (same path as in bundle).
> Fix bundle data path

- src/webpack.config.js
When using SSR, the `window is not defined` error is rasied, see #46.
The issue is with webpack (https://github.com/webpack/webpack/issues/6784), it worked in webpack 3 that is used by original `jm-david/emoji-mart-vue` library, but webpack 4 generates a signature with `window` argument.
Applying the fix as suggested in the comment to the webpack issue - use `globalObject: 'typeof self !== \'undefined\' ? self : this'` for output configuration.
> Fix window is not defined when using SSR

- spec/__snapshots__/picker-spec.js.snap
- src/components/Picker.vue
[#77] Fix: wrong active category (the next category is highlighted as active, not the current one).
> [#77] wrong active category

- docs/app.vue
- spec/picker-spec.js
- spec/picker-static-spec.js
- src/components/Picker.vue
- src/components/StaticPicker.vue
- src/utils/emoji-data.js
[#89] improve preview emoji behavior: log a more explanatory message into the console, use the first emoji available.
This should be more user friendly, as it will be easy to see that first emoji in the UI and change the settings if needed.
> [#89] improve preview emoji behavior

- css/emoji-mart.css
I just scoped the global css rules that affect vue-recycle-scroller
This can lead to this kind of issue with others library that don't use the same rules : 
https://github.com/LouisMazel/vue-phone-number-input/issues/122
> Scoped global css rules of vue-recycle-scroller

- spec/picker-spec.js
- src/components/Picker.vue
[#88] Fix issue on scroll and anchor click
> [#88] Fix scroll issue

- src/utils/frequently.js
For more context/background see https://github.com/nextcloud/nextcloud-vue/issues/2360
```json
{
"+1": 16,
"grinning": 15,
"kissing_heart": 14,
"heart_eyes": 13,
"laughing": 12,
"stuck_out_tongue_winking_eye": 11,
"sweat_smile": 10,
"joy": 9,
"scream": 8,
"disappointed": 7,
"unamused": 6,
"weary": 5,
"sob": 4,
"sunglasses": 3,
"heart": 2,
"poop": 1,
}
```
```json
{
"+1": 5,
"grinning": 4,
"kissing_heart": 4,
"heart_eyes": 4,
"laughing": 4,
"stuck_out_tongue_winking_eye": 3,
"sweat_smile": 3,
"joy": 3,
"scream": 3,
"disappointed": 2,
"unamused": 2,
"weary": 2,
"sob": 2,
"sunglasses": 1,
"heart": 1,
"poop": 1,
}
```
> Populate default emojis in frequently used more sensible

- docs/app.vue
When using custom emojis (like parrot), they are shown as 'undefined' in the output row:
This PR adds another row, with `Emoji` components as output (also keeps the original row with native emojis, but inserts `?` instead of `undefined` for emojis without native representation).
> Fix issue with non-native emoji output in demo app.

- spec/frequently-spec.js
- src/utils/frequently.js
[#152]. Fix the issue with duplicate :hankey: emoji in the frequently used emojis list.
> [#152]. Fix the issue with duplicate :hankey: emoji.

- src/components/anchors.vue
Thanks, for this awesome library!
When it is used in `<form>`, the anchor dispatches `submit` event because `type="button"` attribute is not set.
So the form can be accidentally submitted.
This PR fixes this behavior.
> feat: add type="button" to button in anchors to prevent unintended form submission

- src/components/Emoji.vue
[#204] Fix on click double trigger in Vue 3.
I reproduced this issue in the [vue3 demo project](https://github.com/serebrov/emoji-mart-vue3-demo/commit/6e559709834f8ba1e991dcda3b7a29e097ed5b01), the click handler invoked twice, first with emoji object and second time with `PointerEvent` object.
Related discussion: https://github.com/vuejs/core/issues/813
Adding `emits: ["click"]` to the component definition seems to help and vue 2 project works with this change too.
> [#204] Fix on click double trigger in Vue 3.

- spec/search-spec.js
- src/components/Picker.vue
Prevent default text select event.
In Vue 3 the event goes through the component and triggers the `select` event that is supposed to be emitted only with emoji (there is no such problem in Vue 2).
> [#264] Prevent input 'select' event from propagating to component.

- docs/app.vue
- spec/__snapshots__/picker-spec.js.snap
- spec/picker-spec.js
- src/components/Picker.vue
[#253] Selectable via slot
Prototype selectable picker using custom slot (much simpler then #268, same result).
> [#253] Selectable via slot

- src/components/Picker.vue
Currently changes of properties, especially the `skin` prop, are not reactive.
Meaning you have to close and reload the picker if you change the prop.
So this watches on the prop so that you can modify it and the picker will react (e.g. we want to have the skin tone selector next to the search). Which works and looks like this for us:
https://github.com/serebrov/emoji-mart-vue/assets/1855448/ca8350f4-df24-4c6c-84f1-d4ab6ae2be34
> fix(Picker): Watch for `skin` property changes

- src/components/Picker.vue
- src/components/anchors.vue
- src/components/search.vue
- src/components/skins.vue
This is the same as https://github.com/serebrov/emoji-mart-vue/pull/243 but in the other places that were not covered there.
We encountered this in Safari 17.4.1 where the categories would change on Vue click event correctly but right after that the native click with ClickEvent object as it's first argument would be processed and make the picker completely empty with no way back.
> fix: declare all emits in all components

- src/components/Picker.vue
I encountered that if you are searching emojis while infinite scrolling is disabled in won't show the results.
> fix(picker): show results while infinite scroll is disabled
